### ISSUE TITLE
SDS submission

### ISSUE THREAD

**Issue by oshritush** [oshritush/Speech-Therapy#2]
https://github.com/oshritush/Speech-Therapy/wiki/sds

**Comment by hadarp** [comment]
Checked.
SDS Review Summary and user manual - empty.
SDS page unclear, Please fix the titles to the appropriate content.

**Comment by oshritush** [comment]
SDS page unclear, Please fix the titles to the appropriate content.
what this say? which titles will I need to fix?
Thanks.
